name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.6'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cx-Freeze setuptools

    - name: Build the application
      run: python setup.py build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-macos
        path: build/exe.*

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.6'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cx-Freeze setuptools

    - name: Build the application
      run: python setup.py build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: build/exe.*

    - name: Create installer
      run: python setup.py bdist_msi

    - name: Archive installer
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: dist/*.msi

    - name: Upload PDF Templates
      uses: actions/upload-artifact@v4
      with:
        name: templates
        path: templates/
