name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.6"

    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         pip install pyinstaller
    - name: List installed packages # Log the installed packages for debugging
      run: pip list

    - name: Verify working directory
      run: pwd

    - name: List repository contents
      run: ls -R

    - name: Build executable
      run: |
        pyinstaller --add-data "core/*;core" --add-data "templates/*;templates" main.py
      continue-on-error: true

    - name: List dist directory contents
      run: ls -R dist

    - name: Log pyinstaller output  # Capture detailed pyinstaller logs
      run: cat dist/main/main.spec || echo "main.spec not found"

    - name: Test the executable
      run: |
        ./dist/main/main.exe --version  # Replace this with an appropriate command to test your executable
      continue-on-error: true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: QnE-Python
        path: dist/main

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: dist/main/main.spec
