# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install pyinstaller
    - name: Build executable
      run: |
        pyinstaller --onefile main.py
    - name: List contents of repository
      run: ls -R
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: main-executable
        path: dist/main
